[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/freedom-control/*"
  to = "/freedom-control/index.html"
  status = 200

# Enable Git Gateway for Netlify CMS
[context.production]
  environment = { ACCESS_TOKEN = "", BRANCH = "main" } 