[build]
  publish = "."
  command = "echo 'Using static HTML files'"

[build.environment]
  NODE_VERSION = "18"
  RUBY_VERSION = "3.1.0"

# Jekyll 플러그인을 위한 환경 설정
[context.production.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/freedom-control/*"
  to = "/freedom-control/index.html"
  status = 200

# Enable Git Gateway for Netlify CMS
[context.production]
  environment = { ACCESS_TOKEN = "", BRANCH = "main", JEKYLL_ENV = "production" } 