backend:
  name: git-gateway
  branch: main

# 통합 미디어 관리
media_folder: "images/uploads"
public_folder: "/images/uploads"

# 로컬 미디어 라이브러리 활성화
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"
    multiple: true
    tabs: 'file camera url facebook gdrive gphotos dropbox instagram'
    effects: 'crop,rotate,enhance,grayscale'

collections:
  # ===== 📱 웹사이트 페이지 관리 =====
  - name: "website_pages"
    label: "📱 웹사이트 페이지"
    files:
      # 홈페이지
      - file: "content/homepage.yml"
        label: "🏠 메인 페이지"
        name: "homepage"
        fields:
          - label: "히어로 섹션"
            name: "hero"
            widget: "object"
            fields:
              - { name: "title", label: "메인 제목", widget: "string" }
              - { name: "subtitle", label: "부제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "background_image", label: "배경 이미지", widget: "image" }
              - { name: "cta_text", label: "버튼 텍스트", widget: "string" }
              - { name: "cta_link", label: "버튼 링크", widget: "string" }
          - label: "대표 인사말"
            name: "representative"
            widget: "object"
            fields:
              - { name: "section_title", label: "섹션 제목", widget: "string" }
              - { name: "title", label: "제목", widget: "string" }
              - { name: "name", label: "대표명", widget: "string" }
              - { name: "position", label: "직책", widget: "string" }
              - { name: "photo", label: "대표 사진", widget: "image", required: false }
              - { name: "messages", label: "인사말", widget: "list", field: { name: "message", label: "메시지", widget: "text" } }
          - label: "핵심 정책"
            name: "core_policies"
            widget: "object"
            fields:
              - { name: "section_title", label: "섹션 제목", widget: "string" }
              - name: "policies"
                label: "정책 목록"
                widget: "list"
                fields:
                  - { name: "title", label: "정책명", widget: "string" }
                  - { name: "icon", label: "아이콘", widget: "string" }
                  - { name: "description", label: "설명", widget: "text" }

      # 당에 대해
      - file: "content/about-page.yml"
        label: "🏛️ 당에 대해 (About)"
        name: "about_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - label: "서브 페이지"
            name: "subpages"
            widget: "list"
            fields:
              - { name: "name", label: "페이지명", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "content", label: "내용", widget: "markdown" }
              - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      # 정책 페이지
      - file: "content/policy-page.yml"
        label: "📋 정책 (Policy)"
        name: "policy_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - label: "정책 분야"
            name: "policy_areas"
            widget: "list"
            fields:
              - { name: "area", label: "분야명", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "content", label: "내용", widget: "markdown" }
              - { name: "priority", label: "우선순위", widget: "select", options: ["핵심", "중요", "일반"] }
              - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      # 소식 페이지
      - file: "content/news-page.yml"
        label: "📰 소식 (News)"
        name: "news_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - label: "소식 섹션"
            name: "news_sections"
            widget: "list"
            fields:
              - { name: "section", label: "섹션명", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "content", label: "내용", widget: "markdown" }
              - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      # 참여 페이지
      - file: "content/members-page.yml"
        label: "🤝 참여 (Members)"
        name: "members_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - label: "참여 방법"
            name: "participation_methods"
            widget: "list"
            fields:
              - { name: "method", label: "참여 방법", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "content", label: "내용", widget: "markdown" }
              - { name: "form_action", label: "폼 액션", widget: "string", required: false }
              - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      # 자료실 페이지
      - file: "content/resources-page.yml"
        label: "📚 자료실 (Resources)"
        name: "resources_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - label: "자료 카테고리"
            name: "resource_categories"
            widget: "list"
            fields:
              - { name: "category", label: "카테고리명", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "content", label: "내용", widget: "markdown" }
              - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      # 후원 페이지
      - file: "content/support-page.yml"
        label: "💝 후원 (Support)"
        name: "support_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - { name: "content", label: "내용", widget: "markdown" }
          - { name: "donation_link", label: "후원 링크", widget: "string", required: false }
          - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      # FAQ 페이지
      - file: "content/faq-page.yml"
        label: "❓ FAQ"
        name: "faq_page"
        fields:
          - { name: "page_title", label: "페이지 제목", widget: "string" }
          - { name: "page_description", label: "페이지 설명", widget: "text" }
          - { name: "hero_image", label: "히어로 이미지", widget: "image", required: false }
          - label: "FAQ 목록"
            name: "faqs"
            widget: "list"
            fields:
              - { name: "question", label: "질문", widget: "string" }
              - { name: "answer", label: "답변", widget: "markdown" }
              - { name: "category", label: "카테고리", widget: "select", options: ["일반", "가입", "정책", "활동", "기타"] }

  # ===== 🎬 미디어 센터 =====
  - name: "media_center"
    label: "🎬 미디어 센터"
    files:
      - file: "content/media/images.yml"
        label: "🖼️ 이미지 라이브러리"
        name: "images"
        fields:
          - label: "이미지 컬렉션"
            name: "image_collections"
            widget: "list"
            fields:
              - { name: "title", label: "컬렉션명", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "category", label: "카테고리", widget: "select", options: ["정당 활동", "행사", "정책", "홍보", "기타"] }
              - { name: "date", label: "날짜", widget: "datetime" }
              - label: "이미지들"
                name: "images"
                widget: "list"
                fields:
                  - { name: "image", label: "이미지", widget: "image" }
                  - { name: "caption", label: "캡션", widget: "string", required: false }
                  - { name: "alt_text", label: "대체 텍스트", widget: "string" }

      - file: "content/media/videos.yml"
        label: "🎥 비디오 라이브러리"
        name: "videos"
        fields:
          - label: "비디오 컬렉션"
            name: "video_collections"
            widget: "list"
            fields:
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "category", label: "카테고리", widget: "select", options: ["정당 활동", "행사", "정책 설명", "홍보", "기타"] }
              - { name: "date", label: "날짜", widget: "datetime" }
              - { name: "video_url", label: "동영상 URL", widget: "string" }
              - { name: "thumbnail", label: "썸네일", widget: "image", required: false }
              - { name: "duration", label: "재생 시간", widget: "string", required: false }

      - file: "content/media/documents.yml"
        label: "📄 문서 라이브러리"
        name: "documents"
        fields:
          - label: "문서 컬렉션"
            name: "document_collections"
            widget: "list"
            fields:
              - { name: "title", label: "제목", widget: "string" }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "category", label: "카테고리", widget: "select", options: ["정책 문서", "보도자료", "양식", "매뉴얼", "기타"] }
              - { name: "date", label: "날짜", widget: "datetime" }
              - { name: "file", label: "파일", widget: "file" }
              - { name: "file_type", label: "파일 형식", widget: "string" }
              - { name: "file_size", label: "파일 크기", widget: "string", required: false }

  # ===== 📝 콘텐츠 라이브러리 =====
  - name: "content_library"
    label: "📝 콘텐츠 라이브러리"
    files:
      - file: "content/library/notices.yml"
        label: "📢 공지사항"
        name: "notices"
        fields:
          - label: "공지사항 목록"
            name: "notice_list"
            widget: "list"
            fields:
              - { name: "title", label: "제목", widget: "string" }
              - { name: "date", label: "발행일", widget: "datetime" }
              - { name: "author", label: "작성자", widget: "string", default: "자유와혁신" }
              - { name: "priority", label: "중요도", widget: "select", options: ["일반", "중요", "긴급"] }
              - { name: "category", label: "카테고리", widget: "select", options: ["공지", "보도자료", "성명서", "안내"] }
              - { name: "content", label: "내용", widget: "markdown" }
              - { name: "featured_image", label: "대표 이미지", widget: "image", required: false }

      - file: "content/library/events.yml"
        label: "🎉 행사/집회"
        name: "events"
        fields:
          - label: "행사 목록"
            name: "event_list"
            widget: "list"
            fields:
              - { name: "title", label: "행사명", widget: "string" }
              - { name: "event_date", label: "일시", widget: "datetime" }
              - { name: "location", label: "장소", widget: "string" }
              - { name: "organizer", label: "주최", widget: "string" }
              - { name: "contact", label: "연락처", widget: "string" }
              - { name: "event_type", label: "유형", widget: "select", options: ["집회", "토론회", "간담회", "행진", "세미나", "기타"] }
              - { name: "region", label: "지역", widget: "select", options: ["서울", "부산", "대구", "인천", "광주", "대전", "울산", "세종", "경기", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"] }
              - { name: "description", label: "설명", widget: "text" }
              - { name: "content", label: "상세내용", widget: "markdown" }
              - { name: "poster", label: "포스터", widget: "image", required: false }
              - { name: "fee", label: "참가비", widget: "string", required: false }
              - { name: "registration_required", label: "사전신청", widget: "boolean", default: false }

      - file: "content/library/members.yml"
        label: "👥 주요 인물"
        name: "key_members"
        fields:
          - label: "인물 목록"
            name: "member_list"
            widget: "list"
            fields:
              - { name: "name", label: "이름", widget: "string" }
              - { name: "position", label: "직책", widget: "string" }
              - { name: "order", label: "순서", widget: "number", default: 1 }
              - { name: "photo", label: "프로필 사진", widget: "image", required: false }
              - { name: "contact", label: "연락처", widget: "string", required: false }
              - { name: "email", label: "이메일", widget: "string", required: false }
              - { name: "bio", label: "약력", widget: "markdown" }
              - { name: "experience", label: "주요 경력", widget: "list", field: { name: "career", label: "경력", widget: "string" } }
              - { name: "education", label: "학력", widget: "list", field: { name: "degree", label: "학력", widget: "string" } }

  # ===== ⚙️ 사이트 설정 =====
  - name: "site_settings"
    label: "⚙️ 사이트 설정"
    files:
      - file: "content/settings/site-info.yml"
        label: "🏢 기본 정보"
        name: "site_info"
        fields:
          - { name: "party_name", label: "당명", widget: "string", default: "자유와혁신" }
          - { name: "slogan", label: "슬로건", widget: "string" }
          - { name: "main_phone", label: "대표 연락처", widget: "string" }
          - { name: "main_email", label: "대표 이메일", widget: "string" }
          - { name: "address", label: "주소", widget: "string" }
          - { name: "social_media", label: "소셜 미디어", widget: "object", fields: [
              { name: "facebook", label: "Facebook", widget: "string", required: false },
              { name: "twitter", label: "Twitter", widget: "string", required: false },
              { name: "instagram", label: "Instagram", widget: "string", required: false },
              { name: "youtube", label: "YouTube", widget: "string", required: false }
            ]}
          - { name: "seo_description", label: "SEO 설명", widget: "text" }
          - { name: "site_keywords", label: "사이트 키워드", widget: "string" }

      - file: "content/settings/navigation.yml"
        label: "🧭 네비게이션"
        name: "navigation"
        fields:
          - label: "주 메뉴"
            name: "main_menu"
            widget: "list"
            fields:
              - { name: "title", label: "메뉴명", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "order", label: "순서", widget: "number" }
              - label: "서브 메뉴"
                name: "submenu"
                widget: "list"
                required: false
                fields:
                  - { name: "title", label: "서브메뉴명", widget: "string" }
                  - { name: "url", label: "URL", widget: "string" }

      - file: "logs/changes.log"
        label: "📝 변경 이력"
        name: "changes"
        fields:
          - { name: "body", label: "로그", widget: "markdown" } 