party_name: "자유와혁신"
slogan: "새로운 대한민국을 함께"
main_phone: "02-123-4567"
main_email: "info@jayuhyeksin.kr"
address: "서울특별시 여의도동 국회대로 1"
social_media:
  facebook: ""
  twitter: ""
  instagram: ""
  youtube: ""
membership_url: "https://www.ihappynanum.com/Nanum/api/screen/F7FCRIO2E3"
donation_url: "" 