name: Sync CMS Data to Jekyll

on:
  push:
    paths:
      - '_data/**'
      - 'content/**'

permissions:
  contents: write
  actions: read

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync CMS data to _data folder
        run: |
          echo "🔄 Starting CMS data synchronization..."
          
          # 새로운 CMS 구조에서는 _data 폴더에 직접 저장되므로
          # 별도 동기화가 필요하지 않지만, 미래를 위해 준비
          
          # 홈페이지 통합 데이터 확인
          if [ -f "_data/homepage.yml" ]; then
            echo "✅ Homepage data found"
          fi
          
          # About 페이지 데이터 확인
          if [ -f "content/about-page.yml" ]; then
            echo "✅ About page data found"
          fi
          
          # 미디어 센터 데이터 확인
          if [ -f "content/media/images.yml" ]; then
            echo "✅ Media images data found"
          fi
          
          # 사이트 설정 확인
          if [ -f "content/settings/site-info.yml" ]; then
            echo "✅ Site settings found"
          fi
          
          echo "🎉 CMS data sync check completed"

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔄 자동 동기화: CMS 데이터 업데이트"
            git push
            echo "✅ Changes pushed to repository"
          fi 