name: Sync CMS Data to HTML

on:
  push:
    paths:
      - 'content/homepage.yml'
      - 'content/**'

permissions:
  contents: write
  actions: read

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install PyYAML beautifulsoup4 lxml

      - name: Sync homepage data to index.html
        run: |
          if [ -f "content/homepage.yml" ]; then
            echo "🔄 Syncing homepage data to index.html..."
            
            # Python 스크립트로 안전하게 HTML 업데이트
            python3 << 'EOF'
          import yaml
          import re
          
          try:
              # YAML 데이터 로드
              with open('content/homepage.yml', 'r', encoding='utf-8') as f:
                  data = yaml.safe_load(f)
              
              print("📝 Extracted data:")
              hero_data = data.get('hero', {})
              rep_data = data.get('representative_message', {}).get('representative', {})
              
              hero_title = hero_data.get('title', {})
              if isinstance(hero_title, dict):
                  main_title = hero_title.get('main', '자유와혁신')
                  subtitle = hero_title.get('subtitle', '새로운 정치를 함께')
              else:
                  main_title = '자유와혁신'
                  subtitle = '새로운 정치를 함께'
              
              rep_name = rep_data.get('name', '김○○')
              
              print(f"Hero Title: main: \"{main_title}\"")
              print(f"subtitle: \"{subtitle}\"")
              print(f"style:")
              if 'style' in hero_title:
                  for key, value in hero_title['style'].items():
                      print(f"  {key}: {value}")
              print(f"Hero Subtitle: null")
              print(f"Representative: {rep_name}")
              
              # HTML 파일 읽기
              with open('index.html', 'r', encoding='utf-8') as f:
                  html_content = f.read()
              
              # 간단한 텍스트 교체 (더 안전한 방법)
              if rep_name and rep_name != '김○○':
                  html_content = html_content.replace('김○○', rep_name)
              
              # 업데이트된 HTML 저장
              with open('index.html', 'w', encoding='utf-8') as f:
                  f.write(html_content)
              
              print("✅ Homepage data synchronized successfully!")
              
          except Exception as e:
              print(f"❌ Error: {e}")
              import traceback
              traceback.print_exc()
              exit(1)
          EOF
          
          else
            echo "❌ homepage.yml not found!"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add index.html
            git commit -m "🔄 CMS 동기화: homepage.yml 변경사항을 index.html에 자동 적용"
            git push
            echo "✅ Changes committed and pushed successfully!"
          fi 